ARG VARIANT=3.10
FROM python:${VARIANT}

# assumes a debian variant
RUN apt-get update && apt-get -y install \
  less  \
  vim   \
  libc6 \
  groff \
  nano  \
  postgresql-client \
  silversearcher-ag

ENV APP_HOME /workspaces/python-minecraft-playground
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY requirements.txt .

RUN pip install -r requirements.txt



